<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_out_button</name>
   <tag></tag>
   <elementGuidId>1cb5e415-ce7a-4d0d-a60c-71f0a122f0ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.cart-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.cart-checkout</value>
   </webElementProperties>
</WebElementEntity>
