<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_email</name>
   <tag></tag>
   <elementGuidId>1bbc115e-bb27-4e1a-a33d-9fc7b9185a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[type='email']</value>
   </webElementProperties>
</WebElementEntity>
